sudo: required

services:
  - docker

before_install:
  - docker build -t multi-docker-client-test -f ./client/Dockerfile.dev ./client
    
script:
  - docker run -e CI=true multi-docker-client-test npm run test

after_sucess:
  - docker build -t mattroth/multi-client ./client
  - docker build -t mattroth/multi-nginx ./nginx
  - docker build -t mattroth/multi-server ./server
  - docker build -t mattroth/multi-worker ./worker

#Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin

  - docker push mattroth/multi-client
  - docker push mattroth/multi-nginx
  - docker push mattroth/multi-server
  - docker push mattroth/multi-worker